### PR TITLE
#17 enhancement - Adding Dockerfile & docker compose.yaml

### PR DESCRIPTION
**Pull request by iamkashifyousuf**
Adding Dockerfile & docker-compose.yaml

### CODE REVIEW

**Comment by ritankarsaha** [comment]
@iamkashifyousuf I am grateful that you have contributed to my repository. However this is kinda my personal portfolio website, i wasn't looking for any open source contributions here man. It's my fault, i forgot to setup the guidelines in the repo regarding contributing. The issues i opened basically helps me to remember stuff that i need to do in this website.

However i have quite a repos, which are open-source, you can contribute if you want to. Thanks for stepping up to help. 


Also, @iamkashifyousuf I take it, this is your first time contributing to open-source. You made a little mistake. You made changes in the main branch and pushed the main branch in the codebase. First rule of open source, never push changes in the main branch. What you could do now is:- 


`git log` (helps you to find the latest commit id just after the primary HEAD id)
`git reset --hard <commit id>` (takes you to the last commit when you added and pushed the commit)
`git stash` (stashes your changes)
`git checkout -b "<your-branch-name>"` (to create a new branch)
`git stash pop` (to pop and revert back to the same changes which you made)
`git add ` (adds you changes)
`git commit -m "<commit msg>` 
`git push origin <your-branch-name>`

This was if you made mistakes like this.

In other cases just follow these steps:- 
`git checkout -b "<your-branch-name>"` (to create a new branch)
`git add ` (adds you changes)
`git commit -m "<commit msg>` 
`git push origin <your-branch-name>`


I hope this makes you open-source journey a little easier and you will be able to handle pushing into the branches more gracefully.
Also never force-push. Large codebases will alwyas reject your force-pushed PR's


Thanks once again bro for contributing. If you want, drop an email at ritankar.saha786@gmail.com so that we could have a talk and collaborate on projects together and you may contribute to other repos in my profile which are actually open-source.

Nice Day!!

**Comment by ritankarsaha** [comment]
I am keeping this PR open now, ping me after you have seen the text. Thanks @iamkashifyousuf

**Comment by iamkashifyousuf** [comment]
Hi @ritankarsaha,

Thank you for your message and for clarifying the situation. I apologize for the oversight in contributing directly to the main branch. I appreciate the detailed steps you provided on handling such mistakes and for the guidance on proper open-source contribution practices.

I’m excited about the possibility of collaborating on your other open-source repositories.

Once again, thank you for your understanding and for the opportunity to contribute.

**Comment by ritankarsaha** [comment]
@iamkashifyousuf It's nice I could be of help and you understood the situation. So, I am closing this PR now. @iamkashifyousuf . If you have any more doubts or wanna collaborate on anything together shoot up an email at ritankar.saha786@gmail.com

Thanks, once again.

**Pull request closed without merging**
